Create Table Vaccines (
	vaccineId 	        serial Primary Key,
	CVXcode			        int Not Null,
	shortDesc		        text Not Null,
	vaccineStatus      	text Not Null,
  vaccineGroupName    text Not Null,
  vaccineGroupCVXcode int Not Null,
	notes			          text,
	lastUpdatedDate	timestamp with time zone Not Null Default CURRENT_DATE
);

Insert Into Vaccines (CVXcode, shortDesc, vaccineStatus, vaccineGroupName, vaccineGroupCVXcode)
Values (1, 'DTP', 'Inactive', 'DTAP', 107),
  (2, 'OPV, trivalent', 'Inactive', 'POLIO', 89),
  (3, 'MMR', 'Active', 'MMR', 3),
  (4, 'M/R', 'Inactive', 'MMR', 3),
  (5, 'measles', 'Inactive', 'MMR', 3),
  (6, 'rubella', 'Inactive', 'MMR', 3),
  (7, 'mumps', 'Inactive', 'MMR', 3),
  (8, 'Hep B, adolescent or pediatric', 'Active', 'HepB', 45),
  (9, 'Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed', 'Active', 'Td', 139),
  (10, 'IPV', 'Active', 'POLIO', 89),
  (15, 'influenza, split (incl. purified surface antigen)', 'Inactive', 'FLU', 88),
  (16, 'influenza, whole', 'Inactive', 'FLU', 88),
  (17, 'Hib, unspecified formulation', 'Inactive', 'HIB', 17),
  (18, 'rabies, intramuscular injection', 'Inactive', 'RABIES', 90),
  (19, 'BCG', 'Active', 'BCG', 19),
  (20, 'DTaP', 'Active', 'DTAP', 107),
  (21, 'varicella', 'Active', 'VARICELLA', 21),
  (22, 'DTP-Hib', 'Inactive', 'DTAP', 107),
  (22, 'DTP-Hib', 'Inactive', 'HIB', 17),
  (23, 'plague', 'Inactive', 'Plague', 23),
  (24, 'Anthrax, pre-exposure prophylaxis, post-exposure prophylaxis', 'Active', 'ANTHRAX', 319),
  (25, 'typhoid, oral', 'Active', 'TYPHOID', 91),
  (26, 'cholera, unspecified formulation', 'Inactive', 'cholera', 26),
  (28, 'DT (pediatric)', 'Inactive', 'DTAP', 107),
  (31, 'Hep A, pediatric, unspecified formulation', 'Inactive', 'HepA', 85),
  (32, 'meningococcal MPSV4', 'Inactive', 'MENING', 108),
  (33, 'pneumococcal polysaccharide PPV23', 'Active', 'PneumoPPV', 33),
  (35, 'tetanus toxoid, adsorbed', 'Inactive', 'Td', 139),
  (37, 'yellow fever live', 'Active', 'YELLOWFEVER', 184),
  (38, 'rubella/mumps', 'Inactive', 'MMR', 3),
  (39, 'Japanese encephalitis SC', 'Inactive', 'Japanese encephalitis', 129),
  (40, 'rabies, intradermal injection', 'Inactive', 'RABIES', 90),
  (41, 'typhoid, parenteral', 'Inactive', 'TYPHOID', 91),
  (42, 'Hep B, adolescent/high risk infant', 'Inactive', 'HepB', 45),
  (43, 'Hep B, adult', 'Active', 'HepB', 45),
  (44, 'Hep B, high-dosage, dialysis or IC', 'Active', 'HepB', 45),
  (45, 'Hep B, unspecified formulation', 'Inactive', 'HepB', 45),
  (46, 'Hib (PRP-D)', 'Inactive', 'HIB', 17),
  (47, 'Hib (HbOC)', 'Inactive', 'HIB', 17),
  (48, 'Hib (PRP-T)', 'Active', 'HIB', 17),
  (49, 'Hib (PRP-OMP)', 'Active', 'HIB', 17),
  (50, 'DTaP-Hib', 'Inactive', 'HIB', 17),
  (50, 'DTaP-Hib', 'Inactive', 'DTAP', 107),
  (51, 'Hib-Hep B', 'Inactive', 'HIB', 17),
  (51, 'Hib-Hep B', 'Inactive', 'HepB', 45),
  (52, 'Hep A, adult', 'Active', 'HepA', 85),
  (53, 'typhoid, parenteral, AKD (U.S. military)', 'Inactive', 'TYPHOID', 91),
  (54, 'adenovirus, type 4', 'Inactive', 'ADENO', 82),
  (55, 'adenovirus, type 7', 'Inactive', 'ADENO', 82),
  (56, 'dengue fever tetravalent', 'Active', 'DENGUE', 330),
  (62, 'HPV, quadrivalent', 'Active', 'HPV', 137),
  (66, 'Lyme disease', 'Inactive', 'Lyme disease', 66),
  (74, 'rotavirus, tetravalent', 'Inactive', 'ROTAVIRUS', 122),
  (75, 'Vaccinia (smallpox, monkeypox), live', 'Active', 'Orthopoxvirus', 325),
  (77, 'Tick-borne encephalitis vaccine (non-US)', 'Non-US', 'Tick-borne encephalitis', 222),
  (80, 'VEE, live', 'Inactive', 'VEE', 92),
  (81, 'VEE, inactivated', 'Inactive', 'VEE', 92),
  (82, 'adenovirus, unspecified formulation', 'Inactive', 'ADENO', 82),
  (83, 'Hep A, ped/adol, 2 dose', 'Active', 'HepA', 85),
  (84, 'Hep A, ped/adol, 3 dose', 'Inactive', 'HepA', 85),
  (85, 'Hep A, unspecified formulation', 'Inactive', 'HepA', 85),
  (88, 'influenza, unspecified formulation', 'Inactive', 'FLU', 88),
  (89, 'polio, unspecified formulation', 'Inactive', 'POLIO', 89),
  (90, 'rabies, unspecified formulation', 'Inactive', 'RABIES', 90),
  (91, 'typhoid, unspecified formulation', 'Inactive', 'TYPHOID', 91),
  (92, 'VEE, unspecified formulation', 'Inactive', 'VEE', 92),
  (94, 'MMRV', 'Active', 'MMR', 3),
  (94, 'MMRV', 'Active', 'VARICELLA', 21),
  (100, 'pneumococcal conjugate PCV 7', 'Inactive', 'PneumoPCV', 152),
  (101, 'typhoid, ViCPs', 'Active', 'TYPHOID', 91),
  (102, 'DTP-Hib-Hep B', 'Non-US', 'HIB', 17),
  (102, 'DTP-Hib-Hep B', 'Non-US', 'DTAP', 107),
  (102, 'DTP-Hib-Hep B', 'Non-US', 'HepB', 45),
  (103, 'meningococcal C conjugate', 'Inactive', 'MENING', 108),
  (104, 'Hep A-Hep B', 'Active', 'HepB', 45),
  (104, 'Hep A-Hep B', 'Active', 'HepA', 85),
  (105, 'vaccinia (smallpox) diluted', 'Inactive', 'Orthopoxvirus', 325),
  (106, 'DTaP, 5 pertussis antigens', 'Active', 'DTAP', 107),
  (107, 'DTaP, unspecified formulation', 'Inactive', 'DTAP', 107),
  (108, 'meningococcal ACWY, unspecified formulation', 'Inactive', 'MENING', 108),
  (109, 'pneumococcal, unspecified formulation', 'Inactive', 'PneumoPCV', 152),
  (109, 'pneumococcal, unspecified formulation', 'Inactive', 'PneumoPPV', 33),
  (110, 'DTaP-Hep B-IPV', 'Active', 'DTAP', 107),
  (110, 'DTaP-Hep B-IPV', 'Active', 'HepB', 45),
  (110, 'DTaP-Hep B-IPV', 'Active', 'POLIO', 89),
  (111, 'Influenza, live, trivalent, intranasal, PF', 'Active', 'FLU', 88),
  (113, 'Td (adult), 5 Lf tetanus toxoid, preservative free, adsorbed', 'Active', 'Td', 139),
  (114, 'meningococcal MCV4P', 'Active', 'MENING', 108),
  (115, 'Tdap', 'Active', 'TDAP', 115),
  (116, 'rotavirus, pentavalent', 'Active', 'ROTAVIRUS', 122),
  (118, 'HPV, bivalent', 'Inactive', 'HPV', 137),
  (119, 'rotavirus, monovalent', 'Active', 'ROTAVIRUS', 122),
  (120, 'DTaP-Hib-IPV', 'Active', 'DTAP', 107),
  (120, 'DTaP-Hib-IPV', 'Active', 'HIB', 17),
  (120, 'DTaP-Hib-IPV', 'Active', 'POLIO', 89),
  (121, 'zoster live', 'Inactive', 'ZOSTER', 188),
  (122, 'rotavirus, unspecified formulation', 'Inactive', 'ROTAVIRUS', 122),
  (123, 'influenza, H5N1-1203', 'Inactive', 'H5N1 flu', 123),
  (125, 'Novel Influenza-H1N1-09, nasal', 'Inactive', 'H1N1 flu', 128),
  (126, 'Novel influenza-H1N1-09, preservative-free', 'Inactive', 'H1N1 flu', 128),
  (127, 'Novel influenza-H1N1-09', 'Inactive', 'H1N1 flu', 128),
  (128, 'Novel Influenza-H1N1-09, all formulations', 'Inactive', 'H1N1 flu', 128),
  (129, 'Japanese Encephalitis, unspecified formulation', 'Inactive', 'Japanese encephalitis', 129),
  (130, 'DTaP-IPV', 'Active', 'POLIO', 89),
  (130, 'DTaP-IPV', 'Active', 'DTAP', 107),
  (132, 'DTaP-IPV-HIB-HEP B, historical', 'Inactive', 'POLIO', 89),
  (132, 'DTaP-IPV-HIB-HEP B, historical', 'Inactive', 'HepB', 45),
  (132, 'DTaP-IPV-HIB-HEP B, historical', 'Inactive', 'DTAP', 107),
  (132, 'DTaP-IPV-HIB-HEP B, historical', 'Inactive', 'HIB', 17),
  (133, 'Pneumococcal conjugate PCV 13', 'Active', 'PneumoPCV', 152),
  (134, 'Japanese Encephalitis IM', 'Active', 'Japanese encephalitis', 129),
  (135, 'Influenza, high-dose, trivalent, PF', 'Active', 'FLU', 88),
  (136, 'Meningococcal MCV4O', 'Active', 'MENING', 108),
  (137, 'HPV, unspecified formulation', 'Inactive', 'HPV', 137),
  (138, 'Td (adult)', 'Inactive', 'Td', 139),
  (139, 'Td(adult) unspecified formulation', 'Inactive', 'Td', 139),
  (140, 'Influenza, split virus, trivalent, PF', 'Active', 'FLU', 88),
  (141, 'Influenza, split virus, trivalent, preservative', 'Active', 'FLU', 88),
  (143, 'Adenovirus types 4 and 7', 'Active', 'ADENO', 82),
  (144, 'influenza, seasonal, intradermal, preservative free', 'Inactive', 'FLU', 88),
  (146, 'DTaP,IPV,Hib,HepB', 'Active', 'HIB', 17),
  (146, 'DTaP,IPV,Hib,HepB', 'Active', 'DTAP', 107),
  (146, 'DTaP,IPV,Hib,HepB', 'Active', 'HepB', 45),
  (146, 'DTaP,IPV,Hib,HepB', 'Active', 'POLIO', 89),
  (147, 'meningococcal MCV4, unspecified formulation', 'Inactive', 'MENING', 108),
  (148, 'Meningococcal C/Y-HIB PRP', 'Inactive', 'MENING', 108),
  (148, 'Meningococcal C/Y-HIB PRP', 'Inactive', 'HIB', 17),
  (149, 'Influenza, live, quadrivalent, intranasal', 'Active', 'FLU', 88),
  (150, 'Influenza, split virus, quadrivalent, PF', 'Active', 'FLU', 88),
  (151, 'influenza nasal, unspecified formulation', 'Inactive', 'FLU', 88),
  (152, 'Pneumococcal Conjugate, unspecified formulation', 'Inactive', 'PneumoPCV', 152),
  (153, 'Influenza, MDCK, trivalent, PF', 'Active', 'FLU', 88),
  (155, 'Influenza, recombinant, trivalent, PF', 'Active', 'FLU', 88),
  (158, 'Influenza, split virus, quadrivalent, preservative', 'Active', 'FLU', 88),
  (160, 'Influenza A monovalent (H5N1), ADJUVANTED-2013', 'Active', 'H5N1 flu', 123),
  (161, 'Influenza, injectable,quadrivalent, preservative free, pediatric', 'Active', 'FLU', 88),
  (162, 'meningococcal B, recombinant', 'Active', 'MeningB', 164),
  (163, 'meningococcal B, OMV', 'Active', 'MeningB', 164),
  (164, 'meningococcal B, unspecified', 'Inactive', 'MeningB', 164),
  (165, 'HPV9', 'Active', 'HPV', 137),
  (166, 'influenza, intradermal, quadrivalent, preservative free', 'Inactive', 'FLU', 88),
  (168, 'Influenza, adjuvanted, trivalent, PF', 'Active', 'FLU', 88),
  (170, 'DTAP/IPV/HIB - non-US', 'Non-US', 'POLIO', 89),
  (170, 'DTAP/IPV/HIB - non-US', 'Non-US', 'HIB', 17),
  (170, 'DTAP/IPV/HIB - non-US', 'Non-US', 'DTAP', 107),
  (171, 'Influenza, MDCK, quadrivalent, PF', 'Active', 'FLU', 88),
  (172, 'cholera, WC-rBS', 'Non-US', 'cholera', 26),
  (173, 'cholera, BivWC', 'Non-US', 'cholera', 26),
  (174, 'cholera, live attenuated', 'Active', 'cholera', 26),
  (175, 'Rabies - IM Diploid cell culture', 'Active', 'RABIES', 90),
  (176, 'Rabies - IM fibroblast culture', 'Active', 'RABIES', 90),
  (177, 'PCV10', 'Non-US', 'PneumoPCV', 152),
  (183, 'Yellow fever vaccine live - alt', 'Active', 'YELLOWFEVER', 184),
  (184, 'Yellow fever, unspecified', 'Inactive', 'YELLOWFEVER', 184),
  (185, 'Influenza, recombinant, quadrivalent, PF', 'Active', 'FLU', 88),
  (186, 'Influenza, MDCK, quadrivalent, preservative', 'Active', 'FLU', 88),
  (187, 'zoster recombinant', 'Active', 'ZOSTER', 188),
  (188, 'zoster, unspecified formulation', 'Inactive', 'ZOSTER', 188),
  (189, 'HepB-CpG', 'Active', 'HepB', 45),
  (193, 'Hep A-Hep B, pediatric/adolescent', 'Non-US', 'HepB', 45),
  (193, 'Hep A-Hep B, pediatric/adolescent', 'Non-US', 'HepA', 85),
  (194, 'Influenza, Southern Hemisphere', 'Inactive', 'FLU', 88),
  (195, 'DT, IPV adsorbed', 'Non-US', 'Td', 139),
  (195, 'DT, IPV adsorbed', 'Non-US', 'POLIO', 89),
  (196, 'Td, adsorbed, preservative free, adult use, Lf unspecified', 'Active', 'Td', 139),
  (197, 'Influenza, high-dose, quadrivalent, PF', 'Active', 'FLU', 88),
  (200, 'influenza, Southern Hemisphere, pediatric, preservative free', 'Active', 'FLU', 88),
  (201, 'Influenza, Southern Hemisphere, quadrivalent, PF', 'Active', 'FLU', 88),
  (202, 'influenza, Southern Hemisphere, quadrivalent, with preservative', 'Active', 'FLU', 88),
  (203, 'meningococcal conjugate quadrivalent, MenACWY-TT (MCV4)', 'Active', 'MENING', 108),
  (204, 'Ebola Zaire vaccine, live, recombinant, 1mL dose', 'Active', 'Ebola', 214),
  (205, 'Influenza, adjuvanted, quadrivalent, PF', 'Active', 'FLU', 88),
  (206, 'Vaccinia, smallpox monkeypox vaccine live, PF, SQ or ID injection', 'Active', 'Orthopoxvirus', 325),
  (207, 'COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose', 'Inactive', 'COVID-19', 213),
  (208, 'COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose', 'Inactive', 'COVID-19', 213),
  (210, 'COVID-19 vaccine, vector-nr, rS-ChAdOx1, PF, 0.5 mL', 'Non-US', 'COVID-19', 213),
  (211, 'COVID-19, subunit, rS-nanoparticle+Matrix-M1 Adjuvant, PF, 0.5 mL', 'Inactive', 'COVID-19', 213),
  (212, 'COVID-19 vaccine, vector-nr, rS-Ad26, PF, 0.5 mL', 'Inactive', 'COVID-19', 213),
  (213, 'SARS-COV-2 (COVID-19) vaccine, UNSPECIFIED', 'Inactive', 'COVID-19', 213),
  (214, 'Ebola, unspecified', 'Inactive', 'Ebola', 214),
  (215, 'Pneumococcal conjugate PCV15, polysaccharide CRM197 conjugate, adjuvant, PF', 'Active', 'PneumoPCV', 152),
  (216, 'Pneumococcal conjugate PCV20, polysaccharide CRM197 conjugate, adjuvant, PF', 'Active', 'PneumoPCV', 152),
  (217, 'COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose, tris-sucrose', 'Inactive', 'COVID-19', 213),
  (218, 'COVID-19, mRNA, LNP-S, PF, 10 mcg/0.2 mL dose, tris-sucrose', 'Inactive', 'COVID-19', 213),
  (219, 'COVID-19, mRNA, LNP-S, PF, 3 mcg/0.2 mL dose, tris-sucrose', 'Inactive', 'COVID-19', 213),
  (220, 'HepB recombinant, 3-antigen, Al(OH)3', 'Inactive', 'HepB', 45),
  (221, 'COVID-19, mRNA, LNP-S, PF, 50 mcg/0.5 mL dose', 'Inactive', 'COVID-19', 213),
  (222, 'Tick-borne encephalitis, unspecified', 'Inactive', 'Tick-borne encephalitis', 222),
  (223, 'Tick-borne encephalitis, inactivated, PF, 0.25mL', 'Active', 'Tick-borne encephalitis', 222),
  (224, 'Tick-borne encephalitis, inactivated, PF, 0.5mL', 'Active', 'Tick-borne encephalitis', 222),
  (225, 'COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 5mcg/0.5mL', 'Never Active', 'COVID-19', 213),
  (226, 'COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 10mcg/0.5mL', 'Never Active', 'COVID-19', 213),
  (227, 'COVID-19, mRNA, LNP-S, PF, pediatric 50 mcg/0.5 mL dose', 'Inactive', 'COVID-19', 213),
  (228, 'COVID-19, mRNA, LNP-S, PF, pediatric 25 mcg/0.25 mL dose', 'Inactive', 'COVID-19', 213),
  (229, 'COVID-19, mRNA, LNP-S, bivalent, PF, 50 mcg/0.5 mL or 25mcg/0.25 mL dose', 'Inactive', 'COVID-19', 213),
  (230, 'COVID-19, mRNA, LNP-S, bivalent, PF, 10 mcg/0.2 mL', 'Inactive', 'COVID-19', 213),
  (231, 'influenza, Southern Hemisphere, high-dose, quadrivalent', 'Active', 'FLU', 88),
  (300, 'COVID-19, mRNA, LNP-S, bivalent, PF, 30 mcg/0.3 mL dose', 'Inactive', 'COVID-19', 213),
  (301, 'COVID-19, mRNA, LNP-S, bivalent, PF, 10 mcg/0.2 mL dose', 'Inactive', 'COVID-19', 213),
  (302, 'COVID-19, mRNA, LNP-S, bivalent, PF, 3 mcg/0.2 mL dose', 'Inactive', 'COVID-19', 213),
  (303, 'RSV, recombinant, protein subunit RSVpreF, adjuvant reconstituted, 0.5 mL, PF', 'Active', 'RSV', 304),
  (304, 'Respiratory syncytial virus (RSV), unspecified', 'Inactive', 'RSV', 304),
  (305, 'RSV, bivalent, protein subunit RSVpreF, diluent reconstituted, 0.5 mL, PF', 'Active', 'RSV', 304),
  (306, 'RSV, mAb, nirsevimab-alip, 0.5 mL, neonate to 24 months', 'Active', 'RSV', 304),
  (307, 'RSV, mAb, nirsevimab-alip, 1 mL, neonate to 24 months', 'Active', 'RSV', 304),
  (308, 'COVID-19, mRNA, LNP-S, PF, tris-sucrose, 3 mcg/0.3 mL', 'Inactive', 'COVID-19', 213),
  (309, 'COVID-19, mRNA, LNP-S, PF, tris-sucrose, 30 mcg/0.3 mL', 'Active', 'COVID-19', 213),
  (310, 'COVID-19, mRNA, LNP-S, PF, tris-sucrose, 10 mcg/0.3 mL', 'Active', 'COVID-19', 213),
  (311, 'COVID-19, mRNA, LNP-S, PF, 25 mcg/0.25 mL', 'Active', 'COVID-19', 213),
  (312, 'COVID-19, mRNA, LNP-S, PF, 50 mcg/0.5 mL', 'Active', 'COVID-19', 213),
  (313, 'COVID-19, subunit, rS-nanoparticle, adjuvanted, PF, 5 mcg/0.5 mL', 'Active', 'COVID-19', 213),
  (314, 'Respiratory syncytial virus (RSV) vaccine, unspecified', 'Inactive', 'RSV', 304),
  (315, 'Respiratory syncytial virus (RSV) MAB, unspecified', 'Inactive', 'RSV', 304),
  (316, 'Meningococcal polysaccharide (MenACWY-TT conjugate), (MenB), PF', 'Active', 'MENING', 108),
  (316, 'Meningococcal polysaccharide (MenACWY-TT conjugate), (MenB), PF', 'Active', 'MeningB', 164),
  (317, 'Chikungunya live attenuated vaccine, 0.5 mL, PF', 'Active', 'Chikungunya', 317),
  (318, 'Anthrax, post-exposure prophylaxis', 'Active', 'ANTHRAX', 319),
  (319, 'Anthrax vaccine, unspecified', 'Inactive', 'ANTHRAX', 319),
  (320, 'Influenza, MDCK, trivalent, preservative', 'Active', 'FLU', 88),
  (321, 'Influenza-avian, H5N8, monovalent, PF', 'Active', 'FLU-Avian-H5', 323),
  (322, 'Influenza-avian, H5N8, monovalent, preservative', 'Active', 'FLU-Avian-H5', 323),
  (323, 'Influenza-avian, H5, unspecified formulation', 'Inactive', 'FLU-Avian-H5', 323),
  (324, 'Poliovirus, inactivated, fractional-dose (fIPV)', 'Non-US', 'POLIO', 89),
  (325, 'Vaccinia (smallpox, monkeypox), unspecified', 'Inactive', 'Orthopoxvirus', 325),
  (326, 'RSV, mRNA, injectable, PF', 'Active', 'RSV', 304),
  (327, 'Pneumococcal conjugate PCV21, polysaccharide CRM197 conjugate, PF', 'Active', 'PneumoPCV', 152),
  (328, 'Meningococcal oligosaccharide (MenACWY), (MenB), PF', 'Active', 'MENING', 108),
  (328, 'Meningococcal oligosaccharide (MenACWY), (MenB), PF', 'Active', 'MeningB', 164),
  (329, 'Chikungunya, VLP, recombinant, 0.8 mL, PF', 'Active', 'Chikungunya', 317),
  (330, 'Dengue fever, unspecified', 'Inactive', 'DENGUE', 330),
  (331, 'Influenza, Southern Hemisphere, trivalent, PF', 'Active', 'FLU', 88),
  (332, 'RSV, mAb, clesrovimab-cfor, 0.7 mL, neonate and infant, PF', 'Active', 'RSV', 304),
  (333, 'Influenza, live, trivalent, intranasal, self/caregiver admin, PF', 'Active', 'FLU', 88),
  (334, 'COVID-19, mRNA, LNP-S, PF, 10 mcg/0.2 mL', 'Active', 'COVID-19', 213),
  (500, 'COVID-19 Non-US Vaccine, UNSPECIFIED', 'Non-US', 'COVID-19', 213),
  (501, 'COVID-19 IV Non-US Vaccine (QAZCOVID-IN)', 'Non-US', 'COVID-19', 213),
  (502, 'COVID-19 IV Non-US Vaccine (COVAXIN)', 'Non-US', 'COVID-19', 213),
  (503, 'COVID-19 LAV Non-US Vaccine (COVIVAC)', 'Non-US', 'COVID-19', 213),
  (504, 'COVID-19 VVnr Non-US Vaccine (Sputnik Light)', 'Non-US', 'COVID-19', 213),
  (505, 'COVID-19 VVnr Non-US Vaccine (Sputnik V)', 'Non-US', 'COVID-19', 213),
  (506, 'COVID-19 VVnr Non-US Vaccine (CanSino Biological Inc./Beijing Institute of Biotechnology', 'Non-US', 'COVID-19', 213),
  (507, 'COVID-19 PS Non-US Vaccine (Anhui Zhifei Longcom Biopharm + Inst of Micro, Chinese Acad of Sciences)', 'Non-US', 'COVID-19', 213),
  (508, 'COVID-19 PS Non-US Vaccine (Jiangsu Province Centers for Disease Control and Prevention)', 'Non-US', 'COVID-19', 213),
  (509, 'COVID-19 PS Non-US Vaccine (EpiVacCorona)', 'Non-US', 'COVID-19', 213),
  (510, 'COVID-19 IV Non-US Vaccine (BIBP, Sinopharm)', 'Non-US', 'COVID-19', 213),
  (511, 'COVID-19 IV Non-US Vaccine (CoronaVac, Sinovac)', 'Non-US', 'COVID-19', 213),
  (512, 'SARS-COV-2 COVID-19 VLP Non-US Vaccine (Medicago, Covifenz)', 'Non-US', 'COVID-19', 213),
  (513, 'SARS-COV-2 COVID-19 PS Non-US Vaccine (Anhui Zhifei Longcom, Zifivax)', 'Non-US', 'COVID-19', 213),
  (514, 'SARS-COV-2 COVID-19 DNA Non-US Vaccine (Zydus Cadila, ZyCoV-D)', 'Non-US', 'COVID-19', 213),
  (515, 'SARS-COV-2 COVID-19 PS Non-US Vaccine (Medigen, MVC-COV1901)', 'Non-US', 'COVID-19', 213),
  (516, 'COV-2 COVID-19 Inactivated Non-US Vaccine Product (Minhai Biotechnology Co, KCONVAC)', 'Non-US', 'COVID-19', 213),
  (517, 'SARS-COV-2 COVID-19 PS Non-US Vaccine (Biological E Limited, Corbevax)', 'Non-US', 'COVID-19', 213),
  (518, 'COVID-19 Inactivated, Non-US Vaccine (VLA2001, Valneva)', 'Non-US', 'COVID-19', 213),
  (519, 'COVID-19 mRNA, bivalent, original/Omicron BA.1, Non-US Vaccine (Spikevax Bivalent), Moderna', 'Non-US', 'COVID-19', 213),
  (520, 'COVID-19 mRNA, bivalent, original/Omicron BA.1, Non-US Vaccine Product, Pfizer-BioNTech', 'Non-US', 'COVID-19', 213),
  (521, 'COVID-19 SP, protein-based, adjuvanted (VidPrevtyn Beta), Sanofi-GSK', 'Non-US', 'COVID-19', 213);
